
# Stage 1: Builder - For installing dependencies and setting up the user environment
FROM irvlutd/ubuntu20.04-ros-noetic-base
LABEL version="1.0"
LABEL description="Ubuntu 20.04 + CUDA 11.8 + OpenGL + Vulkan SDK + ROS Noetic + Miniconda3 + Non-root User"


# --------------------- Args for Default User ---------------------
ARG USER_NAME_ARG="my_user"
ARG USER_UID_ARG=1000
ARG USER_GID_ARG=1000

# --------------------- Root User Setup ---------------------
USER root
SHELL ["/bin/bash", "-c"]

# Copy entrypoint script
COPY ./config/my_entrypoint.sh /usr/local/bin/my_entrypoint.sh
RUN chmod +x /usr/local/bin/my_entrypoint.sh
ENTRYPOINT ["/usr/local/bin/my_entrypoint.sh"]

# Create non-root user and group
RUN addgroup --gid ${USER_GID_ARG} ${USER_NAME_ARG} && \
    adduser --disabled-password --home /home/${USER_NAME_ARG} \
    --shell "/bin/zsh" --gecos "" \
    --uid ${USER_UID_ARG} --gid ${USER_GID_ARG} ${USER_NAME_ARG} && \
    usermod -aG sudo ${USER_NAME_ARG} && \
    echo "${USER_NAME_ARG} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME_ARG} && \
    chmod 0440 /etc/sudoers.d/${USER_NAME_ARG}


# --------------------- Switch to my_user for setup ---------------------
USER ${USER_NAME_ARG}
ENV HOME=/home/${USER_NAME_ARG} \
    ZSH_DISABLE_COMPFIX=true
WORKDIR /home/${USER_NAME_ARG}
SHELL ["/bin/zsh", "-c"]

#  Install Oh My Zsh for the newly created user
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended && \
    # change theme to candy
    sed -i 's/ZSH_THEME=".*"/ZSH_THEME="candy"/g' ${HOME}/.zshrc && \
    # disable update check
    zstyle ':omz:update' mode disabled && \
    # Add ROS environment variables to .zshrc for future interactive sessions
    echo "source /opt/ros/noetic/setup.zsh" >> "${HOME}/.zshrc"

# Conda & Environment Setup for the User
RUN source ${HOME}/.zshrc && \
    # Run rosdep update
    rosdep update --rosdistro noetic && \
    /opt/conda/bin/conda init zsh && source ${HOME}/.zshrc && \
    conda config --set auto_activate_base false && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    # Conditionally source ROS setup if it exists
    echo "[ -f ~/catkin_ws/devel/setup.zsh ] && source ~/catkin_ws/devel/setup.zsh" >> ${HOME}/.zshrc && \
    # Conditionally activate Conda environment if it exists
    echo "[ -f ~/code/.env ] && conda activate ~/code/.env" >> ${HOME}/.zshrc

# Create Common Directories (for bind mounts)
RUN mkdir -p ${HOME}/catkin_ws/src && \
    mkdir -p ${HOME}/.gazebo && \
    mkdir -p ${HOME}/.ros

# --------------------- Back to root: Copy EntryPoint ---------------------
USER root
SHELL ["/bin/bash", "-c"]
